/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './footer.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './footer.component';
const styles_FooterComponent:any[] = [i0.styles];
export const RenderType_FooterComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'color_back_20 text-left'],['id','footer']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    Copyright © 2017 Team Awesome. All Rights Reserved\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),
      (null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
      i1.ɵdid(114688,(null as any),0,i2.FooterComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FooterComponentNgFactory:i1.ComponentFactory<i2.FooterComponent> = i1.ɵccf('app-footer',
    i2.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzLkZvb3RlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgaWQ9XCJmb290ZXJcIiBjbGFzcz1cImNvbG9yX2JhY2tfMjAgdGV4dC1sZWZ0XCI+XG4gICAgQ29weXJpZ2h0ICZjb3B5OyAyMDE3IFRlYW0gQXdlc29tZS4gQWxsIFJpZ2h0cyBSZXNlcnZlZFxuPC9kaXY+XG4iLCI8YXBwLWZvb3Rlcj48L2FwcC1mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQSw4QkFBaUQ7TUFFM0M7OztvQkNGTjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
