/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './oauth42.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './oauth42.component';
import * as i4 from '@angular/router';
import * as i5 from '../services/oauth42.service';
const styles_Oauth42Component:any[] = [i0.styles];
export const RenderType_Oauth42Component:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_Oauth42Component,data:{'animation':[{type:7,name:'fade',definitions:[{type:0,
        name:'void',styles:{type:6,styles:{opacity:0},offset:(null as any)},options:(undefined as any)},
        {type:1,expr:':enter',animation:[{type:4,styles:(null as any),timings:300}],
            options:(null as any)}],options:{}}]}});
function View_Oauth42Component_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'loader ma-auto']],(null as any),(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(null as any));
}
export function View_Oauth42Component_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),13,'div',[['class','card-preview-container ma-auto ma-t-30']],
      [[24,'@fade',0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      10,'div',[['class','card card-width-300 ma-auto']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','text-center']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_Oauth42Component_1)),
      i1.ɵdid(16384,(null as any),0,i2.NgIf,[i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
          i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        var _co:i3.Oauth42Component = _v.component;
        const currVal_2:any = _co.pending;
        _ck(_v,12,0,currVal_2);
      },(_ck,_v) => {
        var _co:i3.Oauth42Component = _v.component;
        const currVal_0:any = (undefined as any);
        _ck(_v,1,0,currVal_0);
        const currVal_1:any = _co.status;
        _ck(_v,8,0,currVal_1);
      });
}
export function View_Oauth42Component_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-oauth42',
      ([] as any[]),(null as any),(null as any),(null as any),View_Oauth42Component_0,
      RenderType_Oauth42Component)),i1.ɵdid(114688,(null as any),0,i3.Oauth42Component,
      [i4.ActivatedRoute,i5.Oauth42Service,i4.Router],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const Oauth42ComponentNgFactory:i1.ComponentFactory<i3.Oauth42Component> = i1.ɵccf('app-oauth42',
    i3.Oauth42Component,View_Oauth42Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoNDIvb2F1dGg0Mi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvb2F1dGg0Mi9vYXV0aDQyLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoNDIvb2F1dGg0Mi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoNDIvb2F1dGg0Mi5jb21wb25lbnQudHMuT2F1dGg0MkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGRpdiBAZmFkZSBjbGFzcz1cImNhcmQtcHJldmlldy1jb250YWluZXIgbWEtYXV0byBtYS10LTMwXCI+XG5cbiAgPGRpdiBjbGFzcz1cImNhcmQgY2FyZC13aWR0aC0zMDAgbWEtYXV0b1wiPlxuICAgIDxkaXYgY2xhc3M9XCJ0ZXh0LWNlbnRlclwiPlxuICAgICAgPHA+e3tzdGF0dXN9fTwvcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2ICpuZ0lmPVwicGVuZGluZ1wiIGNsYXNzPVwibG9hZGVyIG1hLWF1dG9cIj48L2Rpdj5cbiAgPC9kaXY+XG5cbjwvZGl2PlxuIiwiPGFwcC1vYXV0aDQyPjwvYXBwLW9hdXRoNDI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ09JO01BQUE7Ozs7b0JBUEosdUNBQ0E7TUFBQTtNQUFBLDJFQUEwRDthQUFBLDRCQUV4RDtNQUFBO01BQUEsNENBQXlDO01BQ3ZDO1VBQUE7TUFBeUIsNkNBQ3ZCO1VBQUE7VUFBQSw4QkFBRyx3Q0FBYztpQkFBQSw0QkFDYjtNQUNOO2FBQUE7VUFBQSx3QkFBa0QseUNBQzlDO2lCQUFBLDBCQUVGOzs7UUFIRztRQUFMLFlBQUssU0FBTDs7O1FBTkM7UUFBTCxXQUFLLFNBQUw7UUFJUztRQUFBOzs7O29CQ0xUO01BQUE7aUNBQUEsVUFBQTtNQUFBOztRQUFBOzs7OyJ9
