/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#profile_avatar[_ngcontent-%COMP%] {\n  position: relative;\n  background-position: center;\n  background-repeat: no-repeat;\n}\n\n#cross[_ngcontent-%COMP%] {\n  position: absolute;\n  right: 0;\n  top: 0;\n  cursor: pointer;\n}\n\n.btn-width[_ngcontent-%COMP%] {\n  width: 100%;\n  max-width: 200px;\n}\n\n.active_cross[_ngcontent-%COMP%] {\n  color: #df2a62;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2VkaXQtcHJvZmlsZS1mb3JtL2VkaXQtcHJvZmlsZS1mb3JtLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvZWRpdC1wcm9maWxlLWZvcm0vZWRpdC1wcm9maWxlLWZvcm0uY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
