/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './oauth-google.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './oauth-google.component';
import * as i4 from '@angular/router';
import * as i5 from '../services/oauth-google.service';
const styles_OauthGoogleComponent:any[] = [i0.styles];
export const RenderType_OauthGoogleComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_OauthGoogleComponent,data:{'animation':[{type:7,name:'fade',definitions:[{type:0,
        name:'void',styles:{type:6,styles:{opacity:0},offset:(null as any)},options:(undefined as any)},
        {type:1,expr:':enter',animation:[{type:4,styles:(null as any),timings:300}],
            options:(null as any)}],options:{}}]}});
function View_OauthGoogleComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'loader ma-auto']],(null as any),(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(null as any));
}
export function View_OauthGoogleComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),13,'div',[['class',
      'card-preview-container ma-auto ma-t-30']],[[24,'@fade',0]],(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),10,'div',[['class','card card-width-300 ma-auto']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','text-center']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n      '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),
          View_OauthGoogleComponent_1)),i1.ɵdid(16384,(null as any),0,i2.NgIf,[i1.ViewContainerRef,
          i1.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i3.OauthGoogleComponent = _v.component;
    const currVal_2:any = _co.loader_pending;
    _ck(_v,15,0,currVal_2);
  },(_ck,_v) => {
    var _co:i3.OauthGoogleComponent = _v.component;
    const currVal_0:any = (undefined as any);
    _ck(_v,4,0,currVal_0);
    const currVal_1:any = _co.status;
    _ck(_v,11,0,currVal_1);
  });
}
export function View_OauthGoogleComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-oauth-google',
      ([] as any[]),(null as any),(null as any),(null as any),View_OauthGoogleComponent_0,
      RenderType_OauthGoogleComponent)),i1.ɵdid(114688,(null as any),0,i3.OauthGoogleComponent,
      [i4.ActivatedRoute,i5.OauthGoogleService,i4.Router],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const OauthGoogleComponentNgFactory:i1.ComponentFactory<i3.OauthGoogleComponent> = i1.ɵccf('app-oauth-google',
    i3.OauthGoogleComponent,View_OauthGoogleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoLWdvb2dsZS9vYXV0aC1nb29nbGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoLWdvb2dsZS9vYXV0aC1nb29nbGUuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvb2F1dGgtZ29vZ2xlL29hdXRoLWdvb2dsZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL29hdXRoLWdvb2dsZS9vYXV0aC1nb29nbGUuY29tcG9uZW50LnRzLk9hdXRoR29vZ2xlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48IS0tPGRpdiBjbGFzcz1cInRleHQtY2VudGVyXCI+LS0+XG4gIDwhLS08cD57e3N0YXR1c319PC9wPi0tPlxuPCEtLTwvZGl2Pi0tPlxuXG48ZGl2IEBmYWRlIGNsYXNzPVwiY2FyZC1wcmV2aWV3LWNvbnRhaW5lciBtYS1hdXRvIG1hLXQtMzBcIj5cblxuICA8ZGl2IGNsYXNzPVwiY2FyZCBjYXJkLXdpZHRoLTMwMCBtYS1hdXRvXCI+XG4gICAgPGRpdiBjbGFzcz1cInRleHQtY2VudGVyXCI+XG4gICAgICA8cD57e3N0YXR1c319PC9wPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgKm5nSWY9XCJsb2FkZXJfcGVuZGluZ1wiIGNsYXNzPVwibG9hZGVyIG1hLWF1dG9cIj48L2Rpdj5cbiAgPC9kaXY+XG5cbjwvZGl2PlxuIiwiPGFwcC1vYXV0aC1nb29nbGU+PC9hcHAtb2F1dGgtZ29vZ2xlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNXSTtNQUFBOzs7O29CQVhKLHVDQUNnQztNQUFBLFdBQ04sdUNBQ2I7TUFBQSxXQUViO01BQUE7TUFBQSw4QkFBMEQsMkNBRXhEO2FBQUE7VUFBQTtNQUF5QywyQ0FDdkM7VUFBQTtVQUFBLDhCQUF5QjtNQUN2QjtVQUFBLDBEQUFHO1VBQUEsVUFBYywyQ0FDYjtVQUFBLGFBQ047VUFBQSxxQ0FBQTt3QkFBQSxtQ0FBeUQ7VUFBQSxXQUNyRCx5Q0FFRjtVQUFBOztJQUhHO0lBQUwsWUFBSyxTQUFMOzs7SUFOQztJQUFMLFdBQUssU0FBTDtJQUlTO0lBQUE7Ozs7b0JDVFQ7TUFBQTtxQ0FBQSxVQUFBO01BQUE7O1FBQUE7Ozs7In0=
