/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.quality_selector[_ngcontent-%COMP%] {\n  display: table-cell;\n  vertical-align: middle;\n  background-color: rgba(0, 0, 0, 0.5);\n  color: white;\n  width: 50px;\n  height: 50px;\n}\n\n.display_table[_ngcontent-%COMP%] {\n  display: table;\n}\n\n.front-img[_ngcontent-%COMP%] {\n  background-repeat: no-repeat !important;\n  background-position: center !important;\n  background-size: cover !important;\n}\n\n.summary-body[_ngcontent-%COMP%] {\n  border-radius: 10px;\n  border: 1px solid lightgrey;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3dhdGNoLXBhZ2Uvd2F0Y2gtcGFnZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3dhdGNoLXBhZ2Uvd2F0Y2gtcGFnZS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
