/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#btn-sign-in[_ngcontent-%COMP%] {\n  min-width: 120px;\n}\n\n.btn-oauth[_ngcontent-%COMP%] {\n  opacity: 0.6;\n  cursor: pointer;\n  display: inline-block;\n  width: 40px;\n  height: 40px;\n  background-position: center !important;\n  background-repeat: no-repeat !important;\n  background-size: contain !important;\n  border: 1px solid lightgrey !important;\n  border-radius: 8px !important;\n}\n\n.btn-oauth[_ngcontent-%COMP%]:hover {\n  box-shadow: 0 0 1px 1px grey;\n  opacity: 1;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3NpZ24taW4tcGFnZS9zaWduLWluLXBhZ2UuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3NlcmovcmVwby9oeXBlcnR1YmUtbmcvc3JjL2FwcC9zaWduLWluLXBhZ2Uvc2lnbi1pbi1wYWdlLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
