/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './nav/nav.component.ngfactory';
import * as i3 from './nav/nav.component';
import * as i4 from './services/auth.service';
import * as i5 from '@angular/router';
import * as i6 from './services/language.service';
import * as i7 from './footer/footer.component.ngfactory';
import * as i8 from './footer/footer.component';
import * as i9 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-nav',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_NavComponent_0,i2.RenderType_NavComponent)),
      i1.ɵdid(114688,(null as any),0,i3.NavComponent,[i4.AuthService,i5.Router,i6.LanguageService],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),
          i1.ɵeld(0,(null as any),(null as any),4,'div',[['id','content-container']],
              (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),
          (null as any),(null as any),i7.View_FooterComponent_0,i7.RenderType_FooterComponent)),
      i1.ɵdid(114688,(null as any),0,i8.FooterComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,6,0);
    _ck(_v,10,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i9.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i9.AppComponent> = i1.ɵccf('app-root',
    i9.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1uYXY+PC9hcHAtbmF2PlxuXG48ZGl2IGlkPVwiY29udGVudC1jb250YWluZXJcIj5cbiAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuPC9kaXY+XG5cbjxhcHAtZm9vdGVyPjwvYXBwLWZvb3Rlcj5cbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUEsNkJBQW1CLHlDQUVuQjtpQkFBQTtjQUFBO01BQTRCLHlDQUMxQjtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCLHVDQUMzQjtNQUVOO1VBQUE7YUFBQTtVQUFBLGVBQXlCO0lBTnpCO0lBR0U7SUFHRjs7OztvQkNOQTtNQUFBO2FBQUE7Ozs7In0=
