/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './my-profile-page.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../edit-profile-form/edit-profile-form.component.ngfactory';
import * as i3 from '../edit-profile-form/edit-profile-form.component';
import * as i4 from '@angular/forms';
import * as i5 from '../services/auth.service';
import * as i6 from '../services/user.service';
import * as i7 from '../services/login.validation.service';
import * as i8 from '../services/email-validation.service';
import * as i9 from '@angular/router';
import * as i10 from './my-profile-page.component';
const styles_MyProfilePageComponent:any[] = [i0.styles];
export const RenderType_MyProfilePageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MyProfilePageComponent,data:{}});
export function View_MyProfilePageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'card-preview-container profile_width ma-auto']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class','card']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h4',[['class',
          'text-center']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['РЕДАКТИРОВАТЬ ПРОФИЛЬ'])),
      (_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'app-edit-profile-form',([] as any[]),(null as any),(null as any),
          (null as any),i2.View_EditProfileFormComponent_0,i2.RenderType_EditProfileFormComponent)),
      i1.ɵdid(114688,(null as any),0,i3.EditProfileFormComponent,[i4.FormBuilder,i5.AuthService,
          i6.UserService,i7.LoginValidationService,i8.EmailValidationService,i9.Router],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
          i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    _ck(_v,8,0);
  },(null as any));
}
export function View_MyProfilePageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-my-profile-page',
      ([] as any[]),(null as any),(null as any),(null as any),View_MyProfilePageComponent_0,
      RenderType_MyProfilePageComponent)),i1.ɵdid(114688,(null as any),0,i10.MyProfilePageComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MyProfilePageComponentNgFactory:i1.ComponentFactory<i10.MyProfilePageComponent> = i1.ɵccf('app-my-profile-page',
    i10.MyProfilePageComponent,View_MyProfilePageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL215LXByb2ZpbGUtcGFnZS9teS1wcm9maWxlLXBhZ2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL215LXByb2ZpbGUtcGFnZS9teS1wcm9maWxlLXBhZ2UuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvbXktcHJvZmlsZS1wYWdlL215LXByb2ZpbGUtcGFnZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL215LXByb2ZpbGUtcGFnZS9teS1wcm9maWxlLXBhZ2UuY29tcG9uZW50LnRzLk15UHJvZmlsZVBhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY2FyZC1wcmV2aWV3LWNvbnRhaW5lciBwcm9maWxlX3dpZHRoIG1hLWF1dG9cIj5cbiAgPGRpdiBjbGFzcz1cImNhcmRcIj5cbiAgICA8aDQgY2xhc3M9XCJ0ZXh0LWNlbnRlclwiXG4gICAgICAgIGkxOG49XCJlZGl0IHByb2ZpbGUgQEBpZF9lZGl0X3Byb2ZpbGVcIj5cbiAgICAgIEVESVQgUFJPRklMRVxuICAgIDwvaDQ+XG4gICAgICAgIDxhcHAtZWRpdC1wcm9maWxlLWZvcm0+PC9hcHAtZWRpdC1wcm9maWxlLWZvcm0+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLW15LXByb2ZpbGUtcGFnZT48L2FwcC1teS1wcm9maWxlLXBhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLDRDQUEwRDtNQUN4RDtVQUFBLDBEQUFrQjtVQUFBLGFBQ2hCO1VBQUE7VUFBQSxnQkFGSjtNQUtTLCtDQUNEO1VBQUE7VUFBQTthQUFBO3NGQUFBO1VBQUEsNkJBQStDLHlDQUMvQztpQkFBQSx3QkFDRjs7SUFGRTs7OztvQkNOUjtNQUFBO3VDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
