/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './sign-up-page.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../sign-up-form/sign-up-form.component.ngfactory';
import * as i3 from '../sign-up-form/sign-up-form.component';
import * as i4 from '@angular/forms';
import * as i5 from '../services/login.validation.service';
import * as i6 from '../services/email-validation.service';
import * as i7 from '../services/user.service';
import * as i8 from '@angular/router';
import * as i9 from './sign-up-page.component';
const styles_SignUpPageComponent:any[] = [i0.styles];
export const RenderType_SignUpPageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SignUpPageComponent,data:{'animation':[{type:7,name:'fade',definitions:[{type:0,
        name:'void',styles:{type:6,styles:{opacity:0},offset:(null as any)},options:(undefined as any)},
        {type:1,expr:':enter',animation:[{type:4,styles:(null as any),timings:300}],
            options:(null as any)}],options:{}}]}});
export function View_SignUpPageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),13,'div',[['class',
      'card-preview-container log_in_width ma-auto ma-t-30']],[[24,'@fade',0]],(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class','card ma-b-60']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h4',[['class','text-center']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['ЗАРЕГИСТРИРОВАТЬСЯ'])),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','text-left ma-t-10']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n\n\n      '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-sign-up-form',([] as any[]),
          (null as any),(null as any),(null as any),i2.View_SignUpFormComponent_0,
          i2.RenderType_SignUpFormComponent)),i1.ɵdid(49152,(null as any),0,i3.SignUpFormComponent,
          [i4.FormBuilder,i5.LoginValidationService,i6.EmailValidationService,i7.UserService,
              i8.Router],(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n\n    '])),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    const currVal_0:any = (undefined as any);
    _ck(_v,0,0,currVal_0);
  });
}
export function View_SignUpPageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-sign-up-page',
      ([] as any[]),(null as any),(null as any),(null as any),View_SignUpPageComponent_0,
      RenderType_SignUpPageComponent)),i1.ɵdid(114688,(null as any),0,i9.SignUpPageComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SignUpPageComponentNgFactory:i1.ComponentFactory<i9.SignUpPageComponent> = i1.ɵccf('app-sign-up-page',
    i9.SignUpPageComponent,View_SignUpPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3NpZ24tdXAtcGFnZS9zaWduLXVwLXBhZ2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3NpZ24tdXAtcGFnZS9zaWduLXVwLXBhZ2UuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9zZXJqL3JlcG8vaHlwZXJ0dWJlLW5nL3NyYy9hcHAvc2lnbi11cC1wYWdlL3NpZ24tdXAtcGFnZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL3NpZ24tdXAtcGFnZS9zaWduLXVwLXBhZ2UuY29tcG9uZW50LnRzLlNpZ25VcFBhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IEBmYWRlIGNsYXNzPVwiY2FyZC1wcmV2aWV3LWNvbnRhaW5lciBsb2dfaW5fd2lkdGggbWEtYXV0byBtYS10LTMwXCI+XG4gIDxkaXYgY2xhc3M9XCJjYXJkIG1hLWItNjBcIj5cbiAgICA8aDQgY2xhc3M9XCJ0ZXh0LWNlbnRlclwiXG4gICAgICAgIGkxOG49XCJAQHNpZ25fdXBfcGFnZV90aXRsZVwiPlxuICAgICAgU0lHTiBVUFxuICAgIDwvaDQ+XG4gICAgPGRpdiBjbGFzcz1cInRleHQtbGVmdCBtYS10LTEwXCI+XG5cblxuICAgICAgPGFwcC1zaWduLXVwLWZvcm0+PC9hcHAtc2lnbi11cC1mb3JtPlxuXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLXNpZ24tdXAtcGFnZT48L2FwcC1zaWduLXVwLXBhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsNENBQXVFO01BQ3JFO1VBQUE7TUFBMEIsMkNBQ3hCO1VBQUE7VUFBQSw4QkFGSjtNQUtTLDJDQUNMO1VBQUE7VUFBQSw4QkFBK0I7TUFHN0I7VUFBQTsyQ0FBQSxVQUFBO1VBQUE7dUJBQUEsK0JBQXFDO1VBQUEsZUFFakMseUNBQ0Y7VUFBQSxTQUNGO0lBYkQ7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDQUE7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
