/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.card[_ngcontent-%COMP%] {\n  background-color: #ffffff;\n  color: #777;\n  padding: 15px;\n  box-shadow: 2px 2px 2px grey;\n  border: 1px solid lightgray;\n}\n\n.card-preview[_ngcontent-%COMP%] {\n  cursor: pointer;\n  padding: 10px;\n  padding-bottom: 20px;\n}\n\n.card-preview[_ngcontent-%COMP%]:hover {\n  box-shadow: 2px 2px 2px 2px grey;\n}\n\n.card-preview-container[_ngcontent-%COMP%] {\n  padding: 5px;\n}\n\n.movie-img[_ngcontent-%COMP%] {\n  display: block;\n  height: 300px;\n  background-size: contain !important;\n  background-repeat: no-repeat !important;\n  background-position: center !important;\n  padding-right: 5px;\n  padding-left: 5px;\n  margin-bottom: 5px;\n}\n\n.card-preview-heading[_ngcontent-%COMP%] {\n  margin-top: 2px;\n  margin-bottom: 10px;\n}\n\n.card-preview-text[_ngcontent-%COMP%] {\n  text-align: left;\n  margin: 0;\n  padding-left: 8px;\n\n}\n\n.watched[_ngcontent-%COMP%] {\n  padding: 2px;\n  display: inline-block;\n  font-size: 10px;\n  color: white;\n  background-color: #777;\n  -webkit-border-radius: 8px;\n  -moz-border-radius: 8px;\n  border-radius: 8px;\n}\n\n.dummy_div[_ngcontent-%COMP%] {\n  padding: 2px;\n  display: inline-block;\n  font-size: 10px;\n  color: white;\n  -webkit-border-radius: 8px;\n  -moz-border-radius: 8px;\n  border-radius: 8px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2Vyai9yZXBvL2h5cGVydHViZS1uZy9zcmMvYXBwL2NhcmQtcHJldmlldy9jYXJkLXByZXZpZXcuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3NlcmovcmVwby9oeXBlcnR1YmUtbmcvc3JjL2FwcC9jYXJkLXByZXZpZXcvY2FyZC1wcmV2aWV3LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
